version: 2.1

workflows:
  version: 2
  build:
    jobs:
      - build

jobs:
  build:
    docker:
      - image: circleci/node:16.0.0
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - run:
          name: installing
          command: npm install
      - run:
          name: starting
          command: node index.js
